import { it, expect, vi } from 'vitest';
import { JSDOM } from 'jsdom';
import { createOperationProfileEditor } from '@isaiandco/ape-share-core/ui/operation-profile-editor';
import { DEFAULT_OPERATION_PROFILES } from '../src/siem/process/operations.js';
it('edits profiles in collapsible fields, saves, validates and resets without silently writing', async () => {
  const dom = new JSDOM('<main></main>');
  const root = dom.window.document.querySelector('main'); const save = vi.fn(async () => {}), status = vi.fn();
  const editor = createOperationProfileEditor({ root, defaults: DEFAULT_OPERATION_PROFILES, save, status });
  editor.set(undefined);
  expect(root.querySelectorAll('details')).toHaveLength(DEFAULT_OPERATION_PROFILES.length);
  root.querySelector('[data-operation-field="pid"]').value = 'datafield1';
  expect(editor.get().profiles[0].pid).toBe('datafield1');
  const click = text => [...root.querySelectorAll('button')].find(button => button.textContent === text).click();
  click('Сохранить профили операций'); await vi.waitFor(() => expect(save).toHaveBeenCalledTimes(1));
  expect(save.mock.calls[0][0].profiles[0].pid).toBe('datafield1');
  root.querySelector('[data-operation-field="pid"]').value = 'bad;field';
  click('Сохранить профили операций'); expect(save).toHaveBeenCalledTimes(1);
  expect(status).toHaveBeenLastCalledWith(expect.stringContaining('недопустимое'), true);
  click('Сбросить к рекомендованным'); expect(editor.get().profiles[0].pid).toBe('subject.process.id');
  expect(save).toHaveBeenCalledTimes(1); dom.window.close();
});

it('adds new recommendations explicitly without overwriting saved profiles, and preserves classifier validation after editing', () => {
  const dom = new JSDOM('<main></main>'); const root = dom.window.document.querySelector('main');
  const editor = createOperationProfileEditor({ root, defaults: DEFAULT_OPERATION_PROFILES, save: async () => {} });
  editor.set([{ ...DEFAULT_OPERATION_PROFILES[0], pid: 'customActor' }]);
  expect(editor.get().profiles).toHaveLength(1);
  const add = [...root.querySelectorAll('button')].find(button => button.textContent === 'Добавить недостающие рекомендуемые профили');
  add.click(); add.click();
  expect(editor.get().profiles).toHaveLength(DEFAULT_OPERATION_PROFILES.length);
  expect(editor.get().profiles[0].pid).toBe('customActor');
  const card = [...root.querySelectorAll('details')].find(item => item.querySelector('summary').textContent.includes('Linux auditd: connect'));
  expect(card.querySelector('input[type="checkbox"]').disabled).toBe(true);
  expect(card.querySelector('[data-operation-readiness]').textContent).toContain('поле типа объекта');
  expect(() => editor.get()).not.toThrow();
  card.querySelector('[data-operation-field="operationField"]').value = 'datafield1';
  card.querySelector('[data-operation-field="operationField"]').dispatchEvent(new dom.window.Event('input'));
  expect(card.querySelector('input[type="checkbox"]').disabled).toBe(false);
  card.querySelector('input[type="checkbox"]').click();
  expect(editor.get().profiles.find(item => item.id === 'auditd-network').selectorRequired).toBe(true);
  dom.window.close();
});
